lang: c
script: "./travis-ci.sh"
env: 
  secure: "VAhcaV0oG7JOTObEWponBaigZmtjhAOOqD4ZuQ1YnERTxcchTGzMg14IYtqAx53D6fhCcAmYA1X1WriwT8NXm+6JoLh+5ErkrRaLVQ4VpW1nd5eDdKh1kRtPVlzPxIelNyFW1EtdEcHVSN9EIBhLiO24k/EGL6YarLL0lm0rYSn8R9r4WgwiU+z9ny+WElxna+hs4XPEV9nOicmsDOJtX49SbjJrEdTL4Rlw4Acg6W9FYh6KqZ5ffa0Vp162K+rlnoQ3zNTpB2+B9mYeDHo97ye1GkeNHwAI94o7mdGxlm1Z3zD23eG4mtCVtf1bW5ihTjxLPHnFatz8WCqL1oBDSnxuQCuRJsMkgelRIOiPdGQwxRnHz1V7z/mqusSiILHEJ7wdmqtfahSGHzhIRTXp7dy06M2iG0yNwSLyOkkmz2uXXo2oxZrWKjKqjhydF7/Sg1muohRf4L2PMZeQP4K0RYoPIJW8fnRaIDZePKp9qyr+qyhC2OFSGQag0KT5atLtHx1VX2bboM4uB7B7sKoe9frdD0QDrO+i5xOcy7pw8/LvcNPDS+f3D11wRfSqvezAiX5S3SvHIGFV2hsG7i1U7rNfXOG/eeCWYyyE5zf9mrapstFZo1IGTnExoB+7rLr3tfPRZ5Mqr5hb8Ai93wcTPtX0YGV7tq7ggUeSUEgo0Ww="
notifications:
  irc:
  - irc.freenode.org#rerun
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq markdown
- sudo apt-get install -qq build-essential
- sudo apt-get install -qq devscripts
- sudo apt-get install -qq dh-make
- sudo apt-get install -qq rpm
BINTRAY_APIKEY=999ea33268d7796006b9793a49092039cccc4ce6aaa6d650f9d208565a19170a:
  secure: YQn4KFlsyyFfmKzyw0sT9dK4wU/iaPwPBPiLT4k+aPLm/PYdRLo7+LBBLyFNUfL/S3spR92sBswse/hY6dWmeMkX8Ds6JGri7dUgfe9dAHQXBjf1P8PPRc4OQRV6MIljAEF025kU5gUwVSt22RmGUp1sghkDWdcRP4QNH7aq1sDKMD7HdNQVc1+qQ7ggoHUz7vQXn2hO5+rRKLLwreeH3bxYJI9v4y5ufu+Z0EHF8i+g+SUWqJ4RH7INp3W3K/qt3OC93k+F/qFWSAp9y8Hvl5Vh/PWFRRzuNpOsFZroovCGlbNnJU3eiv9qJlaX7La9e2vKKgG+A87es7X6wACcVYoX7ualw/G5cGhptKpEfyC5VIhrktXkD56DRFHDxNHFI0o8p6Oa+l+q/ATjMUWyPKdrCSk98pFBvzj0l2cut2DYwkVmPD+WnaVQNZrBSpqiwuX6ShhuIIFJCd6WMfkoL76jZlWNqiJoEWszUngWhSjWT+LDBKcmC8aQatmx/Ob8eb2ID0+GNthh/kEWx+CtYCiXVe9sUSjXvbSo3MFHuW5TIddXCsbGEPShxJ4NRvRv6BYIekB0TqJze+J3e9otNrDSRbY7HR5l7xqWEbeaBfOBZN5l6ke8rtt0nA0cdxdSoVQo5rYcO5J3FYXTfExE1gZ9PfsSyfE+FMCKn08aUyk=
