lang: c
script: "./travis-ci.sh"
env: 
  secure: "S0qOlSpa1pbtHlNXARLY8R2i/ClM9cTRNT/waH5lt4HyyAmBa1QJUFw/y5bR0VE9qiZqJ430QQXQqlSb7COJ4UBCsioyTWtUBm/9hGmFUMU24UE2tPqtA7B2ZsoH1a2JRXN1YbYLW/cWDlO+/0HeqZH4p+3XQEuKn+jtdJ+moIouwhFocV4n/ULMQCBSv/eXLzdxNR3IpuWD/uYtG3KzR/YHq2sxV0ekf72FUQdXo2iPOz79AGQCGK5oBG3gSEMyjPXdnJRR0Ef4259s4nJ6r9YEAGYVkcMOtd6mJTx+hOO5XeD9GIGu0wm2NGF8SZyAp9pn9yUy2qaZnClS8J4wc5CWZtYYbSIIdyS9Lza091IbC5kGcWM8KDI/blSOBZfIJ+mzzU9Pb2vxcSmvJ+zUzlURn8IGgg4nhhnGcUo8oMnE18W8FJGs8DJjv0mSHAN0S/8y9atZx4SVheCA46abhEqD/Joy44WFC5oHPRWmg4gY26gMPxGcM6tLVn4tDq+0lgKDISMfeX8xKJfcRk6GlNScGYN6XOf856GOeZIopidEdMASfCL0EwsabQeYAi/dgODW17j+pxwlw85ttN8fPkDAkDh22Av7P/+wnsyDQ3KJL3KwdLacovo7t5YErUMTSUr+rUxyywAtEhlsEhbuv0luwfmegp2Y0NTEBKiRUxc="
notifications:
  irc:
  - irc.freenode.org#rerun
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq markdown
- sudo apt-get install -qq build-essential
- sudo apt-get install -qq devscripts
- sudo apt-get install -qq dh-make
- sudo apt-get install -qq rpm
