#!/usr/bin/env bash

#/ command: rundeck-system:set-execution-mode: "manage execution mode"
#/ usage: rerun rundeck-system:set-execution-mode [ --format <profile>]  --url <$RUNDECK_URL> [ --username <$RUNDECK_USER>] [ --password <$RUNDECK_PASSWORD>] [ --apikey <$RUNDECK_APIKEY>]  --execution-mode <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: FORMAT URL USERNAME PASSWORD APIKEY EXECUTION_MODE

. $RERUN_MODULE_DIR/lib/functions.sh set-execution-mode || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"



CURL_OUT=$(mktemp -t "curl.out.XXXXX")
POST_CONTENT=$(mktemp -t "post.content.XXXXX")
trap 'rm $CURL_OUT $POST_CONTENT' EXIT; # cleanup on exit

case $EXECUTION_MODE in
	active) APIURL="${URL}/api/14/system/executions/enable"
	;;
	passive) APIURL="${URL}/api/14/system/executions/disable"
	;;
esac


rundeck_authenticate -u "$URL" -U "${USERNAME:-}" -p "${PASSWORD:-}" -k "${APIKEY:-}"

if ! http_code=$(rundeck_curl -w "%{http_code}"  \
	-H Accept:application/xml -H Content-Type:application/xml  \
	-X POST "${APIURL}" -o $CURL_OUT)
then
	rerun_die 3 "curl request failed (exit code: $?)"
fi

case ${http_code:-} in
   	20*) : ;; # successful 
   	40*) rerun_die "$(xmlstarlet sel -t -m //error -v message $CURL_OUT)" ;;
	* )  rerun_die 3 "API error ${http_code:-}: POST ${APIURL}" ;;
esac 

rerun_log info "execution-mode: $(xmlstarlet sel -t -m "/executions" -v @executionMode $CURL_OUT)"

# Done. Exit with last command exit status.
exit $?

