.TH rundeck-loadbalancer-checks 1 "Mon Dec 14 11:08:58 PST 2015" "Version 1.0.0" "RERUN User Manual" 
.SH NAME
rundeck-loadbalancer-checks \- Checks useful for loadbalancer health checks
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] rundeck-loadbalancer-checks: [ is-available | is-quiescent | system-info ] [OPTIONS]
\f[]

.SH COMMANDS
.SH rundeck-loadbalancer-checks:is-available \f[]--thresholds <> --profile <>

the instance is available for traffic
.PP
\f[I]OPTIONS\f[]
.TP
.B \--thresholds \f[]the test thresholds (profile or key=value pairs)\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--profile \f[]the system load profile (use '-' for stdin)\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-loadbalancer-checks:is-quiescent \f[]--thresholds <> --profile <>

the instance is inactive
.PP
\f[I]OPTIONS\f[]
.TP
.B \--thresholds \f[]the test thresholds (profile or key=value pairs)\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--profile \f[]the system load profile (use '-' for stdin)\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH rundeck-loadbalancer-checks:system-info \f[]--url <$RUNDECK_URL> --username <$RUNDECK_USER> --password <$RUNDECK_PASSWORD> [--format <profile>]

get the instance system info
.PP
\f[I]OPTIONS\f[]
.TP
.B \--url \f[]rundeck server url.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]http://targa.local:4440\f[]
.RS
.RE
.TP
.B \--username \f[]the login user name.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]admin\f[]
.RS
.RE
.TP
.B \--password \f[]the login password.\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]admin\f[]
.RS
.RE
.TP
.B \--format \f[]file format (profile,xml)\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]profile\f[]
.RS
.RE ; # command section done.

.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
alexh
.SH "SEE ALSO"
rerun
.SH KEYWORDS
rundeck-loadbalancer-checks
